import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const envFile = path.join(root, 'local.env');
const outFile = path.join(root, 'src', 'environments', 'environment.ts');
const isProduction = process.argv.includes('--production');

const REQUIRED_KEYS = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

function parseEnvFile(content) {
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    vars[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return vars;
}

function loadVariables() {
  const vars = {};

  if (fs.existsSync(envFile)) {
    Object.assign(vars, parseEnvFile(fs.readFileSync(envFile, 'utf8')));
  }

  for (const key of REQUIRED_KEYS) {
    if (process.env[key]) {
      vars[key] = process.env[key];
    }
  }

  const missing = REQUIRED_KEYS.filter((key) => !vars[key]);
  if (missing.length) {
    console.error(
      `\nMissing Firebase config: ${missing.join(', ')}\n` +
        'Copy local.env.example to local.env and fill in your Firebase credentials.\n',
    );
    process.exit(1);
  }

  return vars;
}

const vars = loadVariables();

const environment = {
  production: isProduction,
  firebase: {
    apiKey: vars.FIREBASE_API_KEY,
    authDomain: vars.FIREBASE_AUTH_DOMAIN,
    projectId: vars.FIREBASE_PROJECT_ID,
    storageBucket: vars.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: vars.FIREBASE_MESSAGING_SENDER_ID,
    appId: vars.FIREBASE_APP_ID,
    measurementId: vars.FIREBASE_MEASUREMENT_ID || undefined,
  },
};

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(
  outFile,
  `/** Auto-generated by scripts/load-env.mjs — do not edit manually */\n` +
    `export const environment = ${JSON.stringify(environment, null, 2)} as const;\n`,
);

console.log(`Generated ${path.relative(root, outFile)} (production: ${isProduction})`);
